# --- COMA specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True


runner: "parallel"
go_explore_runner: "go_explore"

buffer_size: 10
batch_size_run: 10
batch_size: 10

bs_agent: "rnn"
mac: "basic_mac"

# ICM setting
imac: "icm_mac"
reward_agent: "icm"
reward_learner: "icm_learner"
icm_lr: 0.0001

# Go Explore setting
just_go_explore: False # False
ge_mac: "go_explore_mac"
mean_repeat: 5
go_action_selector: "bernoulli"

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False


# use COMA
agent_output_type: "pi_logits"
base_learner: "coma_learner"
critic_q_fn: "coma"
standardise_returns: False
standardise_rewards: True

hidden_dim: 64

use_rnn: True
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
entropy_coef: 0.01
q_nstep: 5  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
critic_type: coma_critic

name: "coma"
t_max: 20050000
#######20050000

log_interval: 20000
test_interval: 20000
learner_log_interval: 20000
runner_log_interval: 20000
save_model_interval: 20000
# checkpoint_path: "load"

# save_model: True
