# --- MADDPG specific parameters ---

runner: "episode"

# runner: "parallel"

buffer_size: 5000
# update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False


# use the madddpg_learner to train
mac: "maddpg_mac"
base_learner: "maddpg_learner" # adding
reg: 0.001
batch_size: 10
lr: 0.0001
use_rnn: True

# ICM setting
imac: "icm_mac"
reward_agent: "icm"
reward_learner: "icm_learner"
icm_lr: 0.0001

# Go Explore setting
just_go_explore: False # True
go_explore_runner: "go_explore"
ge_mac: "go_explore_mac"
mean_repeat: 10
go_action_selector: "bernoulli"


standardise_returns: False
standardise_rewards: True

learner: "maddpg_learner"
agent_output_type: "pi_logits"
hidden_dim: 128
critic_type: "maddpg_critic"
name: "maddpg"

log_interval: 20000
test_interval: 20000
learner_log_interval: 20000
runner_log_interval: 20000
save_model_interval: 20000
t_max: 20050000
# buffer_cpu_only: True
save_model: False
